@set pythonpath=src
python tests\scannerTests.py 
python tests\commandTests.py 
python tests\statementTests.py
python tests\runtimeTests.py
python tests\expressionTests.py
python tests\functionTests.py
python tests\matrixTests.py
python tests\readWriteTests.py
python tests\resequencerTests.py
