@set pythonpath=src
python tests\helperTests.py 
python tests\commandTests.py 
python tests\editorTests.py 
python tests\parserTests.py 
python tests\expressionTests.py 
python tests\functionTests.py 
python tests\matrixTests.py 
python tests\readWriteTests.py 
python tests\runTimeTests.py 